#!/bin/bash

#    BuildZone - build a Linux distribution from sourcecode
#    Copyright (C) 2012  Jimmy M. Coleman - hyperclock@web.de
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


# --------------------------------
# debugging output, for less info
# change this line to 'set +ex'
# ------------------------------
set -ex

# ------------------------------------
# Create User "build" if non-existant
# Needs to be done as root
# ------------------------------------
su - root


